
// new patient reducer
export const ADD_NEW_PATIENT_DETAILS = "ADD_NEW_PATIENT_DETAILS";
export const ADD_NEW_PATIENT_DIAGNOSIS = "ADD_NEW_PATIENT_DIAGNOSIS";
export const ADD_NEW_DIAGNOSIS_NUMBER = "ADD_NEW_DIAGNOSIS_NUMBER";
export const CLEAR_NEW_PATIENT = "CLEAR_NEW_PATIENT";



// static data reducer
export const SAVE_ALL_ALLERGENS = "SAVE_ALL_ALLERGENS";
export const SAVE_ALL_PROTOCOLS = "SAVE_ALL_PROTOCOLS";
export const SAVE_LOGIN_USER = "SAVE_LOGIN_USER";
export const SAVE_LOGOUT_USER = "SAVE_LOGOUT_USER";


// Patient reducer
export const ADD_PATIENT_DETAILS = "ADD_PATIENT_DETAILS";
export const ADD_PATIENT_SESSION = "ADD_PATIENT_SESSION";
export const ADD_PATIENT_DIAGNOSIS = "ADD_PATIENT_DIAGNOSIS";
export const CLEAR_PATIENT = "CLEAR_PATIENT";


